Repository keshavgbpecdelhi/Web-Development, pull requests merged in 2022-10, with the labels that each got.

#57 A lil bootstrap porfolio.
  Bootstrap/Little Portfolio/index.html
Labels: hacktoberfest-accepted

#58 Update Readme.md
  README.md
Labels: hacktoberfest-accepted

#61 commit css
  html/Basic_form.html
  html/form.css
Labels: hacktoberfest-accepted

#62 Gradient-Generator for frontend Developer
  Gradient-generator/bggenerator.html
  Gradient-generator/bgjava.js
  Gradient-generator/bgstyle.css
Labels: hacktoberfest-accepted

#66 Updated Readme
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#70 carousel added
  Bootstrap/carousel/index.html
Labels: hacktoberfest-accepted

#71 Added CSS-JS Hybrid Animated Webpage
  CSS-JS Hybrid Animation/README.MD
  CSS-JS Hybrid Animation/dot.png
  CSS-JS Hybrid Animation/index.html
  CSS-JS Hybrid Animation/script.js
  CSS-JS Hybrid Animation/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#85 Auto color changing element using javascript.
  javascript/auto_color_change.js
Labels: Hacktoberfest, hacktoberfest-accepted

#87 added login page file
  loginPage/index.html
  loginPage/style.css
  loginPage/windows.jpg
Labels: Hacktoberfest

#88 added ball game
  ball game/index.html
  ball game/script.js
  ball game/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#99 Dark mode implementaion
  README.md
  simpleDarkmode/ex.css
  simpleDarkmode/ex.html
Labels: Hacktoberfest, hacktoberfest-accepted

#97 Added E-commerce Anime site
  e-commerce/bleach.png
  e-commerce/brand2.png
  e-commerce/brand3.png
  e-commerce/download-removebg-preview.png
  e-commerce/index.html
  e-commerce/logo anime.png
  e-commerce/menuicon.png
  e-commerce/shopping-cart.png
  e-commerce/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#101 Added Roll-the-dice
  Roll-the-Dice/README.md
  Roll-the-Dice/dice.png
  Roll-the-Dice/dicee.js
  Roll-the-Dice/images/dice1.png
  Roll-the-Dice/images/dice2.png
  Roll-the-Dice/images/dice3.png
  Roll-the-Dice/images/dice4.png
  Roll-the-Dice/images/dice5.png
  Roll-the-Dice/images/dice6.png
  Roll-the-Dice/index.html
  Roll-the-Dice/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted

#102 Drum kit was created successfully
  drum-kit/README.md
  drum-kit/images/crash.png
  drum-kit/images/kick.png
  drum-kit/images/snare.png
  drum-kit/images/tom1.png
  drum-kit/images/tom2.png
  drum-kit/images/tom3.png
  drum-kit/images/tom4.png
  drum-kit/index.html
  drum-kit/index.js
  drum-kit/sounds/crash.mp3
  drum-kit/sounds/kick-bass.mp3
  drum-kit/sounds/snare.mp3
  drum-kit/sounds/tom-1.mp3
  drum-kit/sounds/tom-2.mp3
  drum-kit/sounds/tom-3.mp3
  drum-kit/sounds/tom-4.mp3
  drum-kit/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted

#104 Fixed contributing.md bug
  Contributing.md
Labels: Hacktoberfest, hacktoberfest-accepted

#105 Updated the UI of the Event
  .DS_Store
  Event/.DS_Store
  Event/boy.png
  Event/event.css
  Event/event.html
  Event/person1.jpeg
Labels: Hacktoberfest, hacktoberfest-accepted

#113 Update index.html
  javascript/hi_name/index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#117 Added Simon Game
  Simon Game/game.js
  Simon Game/index.html
  Simon Game/sounds/blue.mp3
  Simon Game/sounds/green.mp3
  Simon Game/sounds/red.mp3
  Simon Game/sounds/wrong.mp3
  Simon Game/sounds/yellow.mp3
  Simon Game/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted

#116 Update style.css
  css-1/style.css
Labels: hacktoberfest-accepted

#135 Add new project- Wordle clone
  README.md
  Wordle_Clone/Dictionary.js
  Wordle_Clone/index.html
  Wordle_Clone/script.js
  Wordle_Clone/style.css
Labels: hacktoberfest-accepted

#137 Documentation Page of Java
  html/Documentation.html
Labels: hacktoberfest-accepted

#147 RCF - Random Color Flipper
  Random Color Flipper/Preview.png
  Random Color Flipper/app.js
  Random Color Flipper/index.html
  Random Color Flipper/style.css
Labels: hacktoberfest-accepted

#151 Calculator using HTML,CSS,JS
  calculator2/index.html
  calculator2/script.js
  calculator2/style.css
Labels: hacktoberfest-accepted

#152 SVG Name Project
  Name_Project/index.html
  Name_Project/index.js
  Name_Project/style.css
Labels: hacktoberfest-accepted

#155 added-a-frontend-development course working website
  FRONTEND_COURSE_WEBSITE/fundamentals.svg
  FRONTEND_COURSE_WEBSITE/index.html
  FRONTEND_COURSE_WEBSITE/react.svg
  FRONTEND_COURSE_WEBSITE/showcase.svg
  FRONTEND_COURSE_WEBSITE/style.css
  joke-generator/README.md
  joke-generator/index.html
  joke-generator/script.js
  joke-generator/styles.css
Labels: hacktoberfest-accepted

#157 Created and added Random Joke generator
  Random_Joke_Generator/4265826.ico
  Random_Joke_Generator/index.html
  Random_Joke_Generator/joke.png
  Random_Joke_Generator/script.js
  Random_Joke_Generator/style.css
Labels: hacktoberfest-accepted

#158 Added a new project
  README.md
  mdown-editor/favicon.png
  mdown-editor/index.html
  mdown-editor/script.js
  mdown-editor/style.css
Labels: hacktoberfest-accepted

#160 Added Ball Game
  README.md
  ball game/screenshot/ballGameSS.PNG
Labels: hacktoberfest-accepted

#161 added countdown timer
  README.md
  countdown-timer/README.md
  countdown-timer/assets/tones/Alarm05.wav
  countdown-timer/index.html
  countdown-timer/screenshot/countDownSS.PNG
  countdown-timer/scripts/main.js
  countdown-timer/styles/style.css
Labels: Hacktoberfest

#162 added flipkart clone
  Flipkart clone/Thumbs.db
  Flipkart clone/baseline_shopping_cart_black_24dp.png
  Flipkart clone/img/image1.jpg
  Flipkart clone/index.html
  Flipkart clone/style.css
  README.md
Labels: hacktoberfest-accepted

#164 Analog Watch
  Analog Watch/hp11.html
  Analog Watch/p11.js
Labels: hacktoberfest-accepted

#165 Added Dynamic Quiz
  Dynamic Quiz/index.html
  Dynamic Quiz/script.js
  Dynamic Quiz/style.css
Labels: hacktoberfest-accepted

#166 Added Skills Slider Frontend
  Skill Slider Frontend/index.html
  Skill Slider Frontend/script.js
  Skill Slider Frontend/style.scss
Labels: hacktoberfest-accepted

#172 Cleanup - removed temp thumbnail files
  .DS_Store
  .gitignore
  Event/.DS_Store
  Flipkart clone/Thumbs.db
  dynamic-page/assets/.DS_Store
  dynamic-page/assets/images/discount-product/.DS_Store
  dynamic-page/assets/js/.DS_Store
  fluid-webpage/Fluid-Webpage/images/Thumbs.db
Labels: hacktoberfest-accepted

#170 create login page with responsive
  html/Login.html
Labels: hacktoberfest-accepted

#174 To do weblist
  To-do list Web App/bars-icon.png
  To-do list Web App/index.html
  To-do list Web App/script.js
  To-do list Web App/style.css
Labels: hacktoberfest-accepted

#175 Project Added - Drop down menu with the help of ul li using HTML & CSS
  Drop Down Menu/index.html
  Drop Down Menu/style.css
Labels: hacktoberfest-accepted

#176 multilevel dropdown using html and css
  Multilevel dropdown/index.html
  Multilevel dropdown/style.css
Labels: hacktoberfest-accepted

#177 Added a simple list website
  Simple-list/index.html
  Simple-list/readme.md
  Simple-list/script.js
  Simple-list/style.css
Labels: hacktoberfest-accepted

#179 Loading Screen
  Loading Screen/index.html
  Loading Screen/style.css
Labels: hacktoberfest-accepted

#181 Drawing pad
  Drawing pad/draw.css
  Drawing pad/draw.html
  Drawing pad/script.js
Labels: hacktoberfest-accepted

#182 Food ordering website
  README.md
Labels: hacktoberfest-accepted

#183 Added my palindrome checker site
  palindrome site/index.html
  palindrome site/index.js
  palindrome site/style.css
Labels: hacktoberfest-accepted

#185 Debit Card Ui
  Debit Card/images/bg.jpg
  Debit Card/images/bg2.jpg
  Debit Card/images/bg3.jpg
  Debit Card/images/bob.png
  Debit Card/images/bob2.png
  Debit Card/images/chip.png
  Debit Card/images/chip2.png
  Debit Card/images/map.png
  Debit Card/images/visa.png
  Debit Card/images/visa2.png
  Debit Card/images/wave.png
  Debit Card/index.html
  Debit Card/style.css
Labels: hacktoberfest-accepted

#186 Weather App Added
  Weather App/Weather.jpg
  Weather App/demo/demo.gif
  Weather App/index.html
  Weather App/script.js
  Weather App/style.css
Labels: hacktoberfest-accepted

#187 GitHub profile
  github_profile/index.html
  github_profile/script.js
  github_profile/style.css
Labels: hacktoberfest-accepted

#189 Added the code for Digital clock
  digitalClock/css/style.css
  digitalClock/index.html
  digitalClock/script.js
Labels: hacktoberfest-accepted

#191 Scroll Two Div Parallel
  Scroll Two Div Parallel/Scroll Two Div Parallel.html
Labels: hacktoberfest-accepted

#192 Adding quote generator min project.
  Quote-generator/Quote-generator/index.html
  Quote-generator/Quote-generator/quotes.js
  Quote-generator/Quote-generator/script.js
  Quote-generator/Quote-generator/style.css
Labels: hacktoberfest-accepted

#193 updated with pomodoro webapp
  pomodoro_webapp/bg_pomodoro.png
  pomodoro_webapp/index.html
  pomodoro_webapp/script.js
  pomodoro_webapp/style.css
Labels: hacktoberfest-accepted

#195 Adding Responsive Watches Website
  watch-store/assets/css/styles.css
  watch-store/assets/css/swiper-bundle.min.css
  watch-store/assets/img/favicon.png
  watch-store/assets/img/featured1.png
  watch-store/assets/img/featured2.png
  watch-store/assets/img/featured3.png
  watch-store/assets/img/home.png
  watch-store/assets/img/new1.png
  watch-store/assets/img/new2.png
  watch-store/assets/img/new3.png
  watch-store/assets/img/new4.png
  watch-store/assets/img/product1.png
  watch-store/assets/img/product2.png
  watch-store/assets/img/product3.png
  watch-store/assets/img/product4.png
  watch-store/assets/img/product5.png
  watch-store/assets/img/story.png
  watch-store/assets/img/testimonial.png
  watch-store/assets/img/testimonial1.jpg
  watch-store/assets/img/testimonial2.jpg
  watch-store/assets/img/testimonial3.jpg
  watch-store/assets/index.html
  watch-store/assets/js/main.js
  watch-store/assets/js/swiper-bundle.min.js
  watch-store/assets/scss/base/_base.scss
  watch-store/assets/scss/components/_breakpoints.scss
  watch-store/assets/scss/components/_buttons.scss
  watch-store/assets/scss/components/_cart.scss
  watch-store/assets/scss/components/_featured.scss
  watch-store/assets/scss/components/_footer.scss
  watch-store/assets/scss/components/_header.scss
  watch-store/assets/scss/components/_home.scss
  watch-store/assets/scss/components/_new.scss
  watch-store/assets/scss/components/_newsletter.scss
  watch-store/assets/scss/components/_products.scss
  watch-store/assets/scss/components/_scroll.scss
  watch-store/assets/scss/components/_story.scss
  watch-store/assets/scss/components/_testimonial.scss
  watch-store/assets/scss/config/_variables.scss
  watch-store/assets/scss/layout/_layout.scss
  watch-store/assets/scss/styles.scss
  watch-store/assets/scss/theme/_theme.scss
Labels: hacktoberfest-accepted

#198 Added PHP Enabled html project
  php-1/index.html
Labels: hacktoberfest-accepted

#199 [FEATURE] Memory-games #194Add files via upload
  Memory-game/README.md
  Memory-game/image/allemo.png
  Memory-game/image/angryface.png
  Memory-game/image/coolface.png
  Memory-game/image/evilface.png
  Memory-game/image/feverface.png
  Memory-game/image/freezeface.png
  Memory-game/image/mindblownface.png
  Memory-game/image/sneezeface.png
  Memory-game/image/thinkingface.png
  Memory-game/image/vomitface.png
  Memory-game/index.html
  Memory-game/index.js
  Memory-game/styles.css
Labels: hacktoberfest-accepted

#200 Random Quote Generator added
  Random Quote Generator/Readme.md
  Random Quote Generator/index.html
  Random Quote Generator/script.js
  Random Quote Generator/style.css
Labels: hacktoberfest-accepted

#201 Fixed Readme Table : Added few recent list of Projects
  README.md
Labels: hacktoberfest-accepted

#203 Create index.html
  twitterLogoCssOnly/index.html
Labels: hacktoberfest-accepted

#205 A simple survey form using html
  html/survey_form.html
Labels: hacktoberfest-accepted

#208 Get Random Advice- react app
  Get Random Advice/README.md
  Get Random Advice/package-lock.json
  Get Random Advice/package.json
  Get Random Advice/public/favicon.ico
  Get Random Advice/public/index.html
  Get Random Advice/public/logo192.png
  Get Random Advice/public/logo512.png
  Get Random Advice/public/manifest.json
  Get Random Advice/public/robots.txt
  Get Random Advice/src/App.css
  Get Random Advice/src/App.js
  Get Random Advice/src/images/bg.jpg
  Get Random Advice/src/index.js
Labels: hacktoberfest-accepted

#209 Random color Generator
  Random-color-Generator/bing.mpeg
  Random-color-Generator/index.html
  Random-color-Generator/index.js
  Random-color-Generator/readme.md
  Random-color-Generator/style.css
Labels: hacktoberfest-accepted

#212 online mock test demo
  OnlineMockTestSystem/index.html
Labels: hacktoberfest-accepted

#213 added alt text in img tags
  FRONTEND_COURSE_WEBSITE/index.html
Labels: hacktoberfest-accepted

#214 Chrome extension to check internet connection
  Check Internet Connection Status/images.png
  Check Internet Connection Status/index.html
  Check Internet Connection Status/manifest.json
  Check Internet Connection Status/script.js
  Check Internet Connection Status/style.css
Labels: hacktoberfest-accepted

#215 Disk Scheduling Algorithms using HTML CSS and JS
  DiskSchedulingAlgorithms/DiscScheduling.css
  DiskSchedulingAlgorithms/cscan.js
  DiskSchedulingAlgorithms/cscan1.html
  DiskSchedulingAlgorithms/fcfs.js
  DiskSchedulingAlgorithms/fcfs1.html
  DiskSchedulingAlgorithms/index.html
  DiskSchedulingAlgorithms/scan.js
  DiskSchedulingAlgorithms/scan1.html
  DiskSchedulingAlgorithms/sstf.js
  DiskSchedulingAlgorithms/sstf1.html
Labels: hacktoberfest-accepted

#221 Fixed hover styles of the buttons which were not working in index.html
  FRONTEND_COURSE_WEBSITE/index.html
  FRONTEND_COURSE_WEBSITE/style.css
Labels: hacktoberfest-accepted

#222 Create Browser.py
  Browser/Browser.py
Labels: hacktoberfest-accepted

#224 Created Screen Recorder
  Screen Recorder/main.py
Labels: hacktoberfest-accepted

#225 fixed style tag which was not correct added / .
  twitterLogoCssOnly/index.html
Labels: hacktoberfest-accepted

#226 Added Digital Marketing Landing Page
  Digital Marketing Landing Page/assets/css/bootstrap.min.css
  Digital Marketing Landing Page/assets/css/flex-slider.css
  Digital Marketing Landing Page/assets/css/font-awesome.css
  Digital Marketing Landing Page/assets/css/templatemo-softy-pinko.css
  Digital Marketing Landing Page/assets/fonts/Flaticon.woff
  Digital Marketing Landing Page/assets/fonts/FontAwesome.otf
  Digital Marketing Landing Page/assets/fonts/flexslider-icon.eot
  Digital Marketing Landing Page/assets/fonts/flexslider-icon.svg
  Digital Marketing Landing Page/assets/fonts/flexslider-icon.ttf
  Digital Marketing Landing Page/assets/fonts/flexslider-icon.woff
  Digital Marketing Landing Page/assets/fonts/fontawesome-webfont.eot
  Digital Marketing Landing Page/assets/fonts/fontawesome-webfont.svg
  Digital Marketing Landing Page/assets/fonts/fontawesome-webfont.ttf
  Digital Marketing Landing Page/assets/fonts/fontawesome-webfont.woff
  Digital Marketing Landing Page/assets/fonts/fontawesome-webfont.woff2
  Digital Marketing Landing Page/assets/fonts/slick.eot
  Digital Marketing Landing Page/assets/fonts/slick.svg
  Digital Marketing Landing Page/assets/fonts/slick.ttf
  Digital Marketing Landing Page/assets/fonts/slick.woff
  Digital Marketing Landing Page/assets/images/banner-bg.png
  Digital Marketing Landing Page/assets/images/blog-item-01.png
  Digital Marketing Landing Page/assets/images/blog-item-02.png
  Digital Marketing Landing Page/assets/images/blog-item-03.png
  Digital Marketing Landing Page/assets/images/circle-dec.png
  Digital Marketing Landing Page/assets/images/featured-item-01.png
  Digital Marketing Landing Page/assets/images/fun-facts-bg.png
  Digital Marketing Landing Page/assets/images/left-image.png
  Digital Marketing Landing Page/assets/images/logo.png
  Digital Marketing Landing Page/assets/images/right-image.png
  Digital Marketing Landing Page/assets/images/testimonial-icon.png
  Digital Marketing Landing Page/assets/images/work-process-bg.png
  Digital Marketing Landing Page/assets/images/work-process-item-01.png
  Digital Marketing Landing Page/assets/js/bootstrap.min.js
  Digital Marketing Landing Page/assets/js/custom.js
  Digital Marketing Landing Page/assets/js/imgfix.min.js
  Digital Marketing Landing Page/assets/js/jquery-2.1.0.min.js
  Digital Marketing Landing Page/assets/js/jquery.counterup.min.js
  Digital Marketing Landing Page/assets/js/popper.js
  Digital Marketing Landing Page/assets/js/scrollreveal.min.js
  Digital Marketing Landing Page/assets/js/waypoints.min.js
  Digital Marketing Landing Page/index.html
  Digital Marketing Landing Page/prepros-6.config
Labels: hacktoberfest-accepted

#228 fixed clock-text in center with text-align center
  Animated_Clock/watch.css
Labels: hacktoberfest-accepted

#232 Add responsive login form
  html/login-from.html
Labels: hacktoberfest-accepted

#233 added drumkit JS Project
  drumkit/images/crash.png
  drumkit/images/icon.png
  drumkit/images/kick.png
  drumkit/images/snare.png
  drumkit/images/tom1.png
  drumkit/images/tom2.png
  drumkit/images/tom3.png
  drumkit/images/tom4.png
  drumkit/index.html
  drumkit/index.js
  drumkit/sounds/crash.mp3
  drumkit/sounds/kick-bass.mp3
  drumkit/sounds/snare.mp3
  drumkit/sounds/tom-1.mp3
  drumkit/sounds/tom-2.mp3
  drumkit/sounds/tom-3.mp3
  drumkit/sounds/tom-4.mp3
  drumkit/styles.css
Labels: hacktoberfest-accepted

#234 Created 2048 game using html, css and javascript
  2048 Game/app.js
  2048 Game/index.html
  2048 Game/style.css
Labels: hacktoberfest-accepted

#236 Added Speed Typing Game
  Speed Typing Game/index.html
  Speed Typing Game/script.js
Labels: hacktoberfest-accepted

#238 Added Startup Landing Page
  Startup Landing Page/CHANGELOG.md
  Startup Landing Page/dist/css/style.css
  Startup Landing Page/dist/images/cta-illustration.svg
  Startup Landing Page/dist/images/feature-icon-01.svg
  Startup Landing Page/dist/images/feature-icon-02.svg
  Startup Landing Page/dist/images/feature-icon-03.svg
  Startup Landing Page/dist/images/feature-icon-04.svg
  Startup Landing Page/dist/images/feature-icon-05.svg
  Startup Landing Page/dist/images/feature-icon-06.svg
  Startup Landing Page/dist/images/hero-back-illustration.svg
  Startup Landing Page/dist/images/hero-top-illustration.svg
  Startup Landing Page/dist/images/logo.svg
  Startup Landing Page/dist/images/pricing-illustration.svg
  Startup Landing Page/dist/js/main.min.js
  Startup Landing Page/index.html
  Startup Landing Page/package-sample.json
  Startup Landing Page/src/images/cta-illustration.svg
  Startup Landing Page/src/images/feature-icon-01.svg
  Startup Landing Page/src/images/feature-icon-02.svg
  Startup Landing Page/src/images/feature-icon-03.svg
  Startup Landing Page/src/images/feature-icon-04.svg
  Startup Landing Page/src/images/feature-icon-05.svg
  Startup Landing Page/src/images/feature-icon-06.svg
  Startup Landing Page/src/images/hero-back-illustration.svg
  Startup Landing Page/src/images/hero-top-illustration.svg
  Startup Landing Page/src/images/logo.svg
  Startup Landing Page/src/images/pricing-illustration.svg
  Startup Landing Page/src/js/main.js
  Startup Landing Page/src/scss/_normalize.scss
  Startup Landing Page/src/scss/abstracts/_functions.scss
  Startup Landing Page/src/scss/abstracts/_include-media.scss
  Startup Landing Page/src/scss/abstracts/_mixins.scss
  Startup Landing Page/src/scss/abstracts/_variables.scss
  Startup Landing Page/src/scss/base/_base.scss
  Startup Landing Page/src/scss/base/_helpers.scss
  Startup Landing Page/src/scss/base/_typography.scss
  Startup Landing Page/src/scss/components/_buttons.scss
  Startup Landing Page/src/scss/components/_forms.scss
  Startup Landing Page/src/scss/layout/_cta.scss
  Startup Landing Page/src/scss/layout/_features.scss
  Startup Landing Page/src/scss/layout/_footer.scss
  Startup Landing Page/src/scss/layout/_header.scss
  Startup Landing Page/src/scss/layout/_hero.scss
  Startup Landing Page/src/scss/layout/_main.scss
  Startup Landing Page/src/scss/layout/_pricing.scss
  Startup Landing Page/src/scss/style.scss
Labels: hacktoberfest-accepted

#240 tv-show search app
  TV-show Search app/index.html
  TV-show Search app/script.js
Labels: hacktoberfest-accepted

#243 added alt text on play button
  Spotify/index.html
Labels: hacktoberfest-accepted

#244 Mole in a Hole Game
  Mole in a Hole Game/cartoon-cute-mole-260nw-274323440.png
  Mole in a Hole Game/index.html
  Mole in a Hole Game/index.js
  Mole in a Hole Game/pngtree-cartoon-red-trap-free-illustration-image_2285435.png
  Mole in a Hole Game/style.css
Labels: hacktoberfest-accepted

#246 Create main.py
  PDF Password Opener/main.py
Labels: hacktoberfest-accepted

#247 Added metrics calculator project
  Metrics Calculator/capasitance.html
  Metrics Calculator/current.html
  Metrics Calculator/index.html
  Metrics Calculator/length.html
  Metrics Calculator/resistance.html
  Metrics Calculator/speed.html
  Metrics Calculator/temprature.html
  Metrics Calculator/vendors/animate.css
  Metrics Calculator/vendors/bootstrap.min.css
  Metrics Calculator/vendors/fonts.js
  Metrics Calculator/vendors/main.js
  Metrics Calculator/vendors/style.css
  Metrics Calculator/vendors/styleMain.css
  Metrics Calculator/volume.html
  Metrics Calculator/weight.html
Labels: hacktoberfest-accepted

#250 Added stopwatch timer app
  Timer App/index.html
  Timer App/index.js
  Timer App/style.css
  Timer App/timer.js
Labels: hacktoberfest-accepted

#251 Flipping login card
  Flipping_Login_card/index.htm
  Flipping_Login_card/login_styles.css
Labels: hacktoberfest-accepted

#254 Added Basic Responsive Bootstrap Website
  Responsive Bootstrap Website/Images/img1.jpg
  Responsive Bootstrap Website/Images/img2.jpg
  Responsive Bootstrap Website/Images/img3.jpg
  Responsive Bootstrap Website/Images/img4.jpg
  Responsive Bootstrap Website/Images/img5.jpg
  Responsive Bootstrap Website/Images/img6.jpg
  Responsive Bootstrap Website/about.html
  Responsive Bootstrap Website/contact.html
  Responsive Bootstrap Website/gallery.html
  Responsive Bootstrap Website/index.html
  Responsive Bootstrap Website/style.css
Labels: hacktoberfest-accepted

#255 Added Countdown Timer
  Countdown-Timer/app.js
  Countdown-Timer/index.html
  Countdown-Timer/style.css
Labels: hacktoberfest-accepted

#259 added JS Maze Game
  Maze Game/index.html
  Maze Game/index.js
Labels: hacktoberfest-accepted

#260 added snake game
  snake game/index.html
Labels: hacktoberfest-accepted

#261 Contact Form
  ContactForm/ContactForm.md
  ContactForm/index.html
  ContactForm/style.css
Labels: hacktoberfest-accepted

#262 Added YouTube clone
  Youtube-Clone/README.md
  Youtube-Clone/assets/images/favicon1.ico
  Youtube-Clone/assets/images/ganesh.jpg
  Youtube-Clone/assets/images/hero.png
  Youtube-Clone/assets/images/profile.jpg
  Youtube-Clone/assets/script.js
  Youtube-Clone/assets/style.css
  Youtube-Clone/assets/videos.json
  Youtube-Clone/index.html
  Youtube-Clone/package-lock.json
  Youtube-Clone/package.json
  Youtube-Clone/style.css
  Youtube-Clone/tailwind.config.js
Labels: hacktoberfest-accepted

#263 Adding payment form in the repository
  Payment-Form/payment_form.html
  Payment-Form/style2.css
Labels: hacktoberfest-accepted

#265 Eyes Moving
  Eyes Moving/eye_ball.png
  Eyes Moving/index.html
  Eyes Moving/index.js
  Eyes Moving/style.css
Labels: hacktoberfest-accepted

#269 Create index.html
  Quiz-app/index.html
Labels: hacktoberfest-accepted

#270 Added myntra clone
  Myntra-Clone-main/README.md
  Myntra-Clone-main/home.png
  Myntra-Clone-main/index.html
  Myntra-Clone-main/style.css
  Myntra-Clone-main/utils.css
Labels: hacktoberfest-accepted

#273 Add html and css files for the given contact form.
  Contact us form/index.css
  Contact us form/login.html
Labels: hacktoberfest-accepted

#274 Note Pad project
  Note_Pad/app.js
  Note_Pad/index.html
Labels: hacktoberfest-accepted

#275 Profile Cards With Slider
  ProfileCardsWithSlider/Images/Muskan Mishra.jpeg
  ProfileCardsWithSlider/Profile Card With Slider preview.PNG
  ProfileCardsWithSlider/ProfileCardsWithSlider.md
  ProfileCardsWithSlider/index.html
  ProfileCardsWithSlider/style.css
Labels: hacktoberfest-accepted

#276 added socket.io chat app
  Socket IO Chat App/.gitignore
  Socket IO Chat App/_html_css/chat.html
  Socket IO Chat App/_html_css/css/style.css
  Socket IO Chat App/_html_css/index.html
  Socket IO Chat App/_html_css/js/main.js
  Socket IO Chat App/package-lock.json
  Socket IO Chat App/package.json
  Socket IO Chat App/public/chat.html
  Socket IO Chat App/public/css/style.css
  Socket IO Chat App/public/index.html
  Socket IO Chat App/public/js/main.js
  Socket IO Chat App/server.js
  Socket IO Chat App/utils/messages.js
  Socket IO Chat App/utils/users.js
Labels: hacktoberfest-accepted

#283 add convert web app
  Convert/index.html
  Convert/public/favicon.png
  Convert/public/index.js
  Convert/public/style.css
Labels: hacktoberfest-accepted
